version: "2"
run:
  modules-download-mode: readonly
  tests: true
output:
  formats:
    text:
      path: stdout
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    revive:
      rules:
        - name: var-naming
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
          - gosec
          - revive
        path: _test\.go
      - linters:
          - all
        path: \.pb\.go$
      - linters:
          - all
        path: zz_generated\.
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
