package ai

// Code generated from packages/ai/src/image-models.generated.ts in badlogic/pi-mono; DO NOT EDIT.

func init() {
	RegisterImageModels(generatedImageModels...)
}

var generatedImageModels = []ImagesModel{
	{
		Provider: "openrouter",
		ID:       "black-forest-labs/flux.2-flex",
		Name:     "Black Forest Labs: FLUX.2 Flex",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "black-forest-labs/flux.2-klein-4b",
		Name:     "Black Forest Labs: FLUX.2 Klein 4B",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "black-forest-labs/flux.2-max",
		Name:     "Black Forest Labs: FLUX.2 Max",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "black-forest-labs/flux.2-pro",
		Name:     "Black Forest Labs: FLUX.2 Pro",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "bytedance-seed/seedream-4.5",
		Name:     "ByteDance Seed: Seedream 4.5",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"image", "text"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "google/gemini-2.5-flash-image",
		Name:     "Google: Nano Banana (Gemini 2.5 Flash Image)",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     Cost{Input: 0.3, Output: 2.5, CacheRead: 0.03, CacheWrite: 0.08333333333333334},
	},
	{
		Provider: "openrouter",
		ID:       "google/gemini-3-pro-image-preview",
		Name:     "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     Cost{Input: 2, Output: 12, CacheRead: 0.19999999999999998, CacheWrite: 0.375},
	},
	{
		Provider: "openrouter",
		ID:       "google/gemini-3.1-flash-image-preview",
		Name:     "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     Cost{Input: 0.5, Output: 3, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "microsoft/mai-image-2.5",
		Name:     "Microsoft: MAI-Image-2.5",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 5, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "openai/gpt-5-image",
		Name:     "OpenAI: GPT-5 Image",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     Cost{Input: 10, Output: 10, CacheRead: 1.25, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "openai/gpt-5-image-mini",
		Name:     "OpenAI: GPT-5 Image Mini",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     Cost{Input: 2.5, Output: 2, CacheRead: 0.25, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "openai/gpt-5.4-image-2",
		Name:     "OpenAI: GPT-5.4 Image 2",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"image", "text"},
		Output:   []string{"image", "text"},
		Cost:     Cost{Input: 8, Output: 15, CacheRead: 2, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "openrouter/auto",
		Name:     "Auto Router",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"text", "image"},
		Cost:     Cost{Input: -1000000, Output: -1000000, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v3",
		Name:     "Recraft: Recraft V3",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4",
		Name:     "Recraft: Recraft V4",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4-pro",
		Name:     "Recraft: Recraft V4 Pro",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4-pro-vector",
		Name:     "Recraft: Recraft V4 Pro Vector",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4-vector",
		Name:     "Recraft: Recraft V4 Vector",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4.1",
		Name:     "Recraft: Recraft V4.1",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4.1-pro",
		Name:     "Recraft: Recraft V4.1 Pro",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4.1-pro-vector",
		Name:     "Recraft: Recraft V4.1 Pro Vector",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4.1-utility",
		Name:     "Recraft: Recraft V4.1 Utility",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4.1-utility-pro",
		Name:     "Recraft: Recraft V4.1 Utility Pro",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "recraft/recraft-v4.1-vector",
		Name:     "Recraft: Recraft V4.1 Vector",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "sourceful/riverflow-v2-fast",
		Name:     "Sourceful: Riverflow V2 Fast",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "sourceful/riverflow-v2-fast-preview",
		Name:     "Sourceful: Riverflow V2 Fast Preview",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "sourceful/riverflow-v2-max-preview",
		Name:     "Sourceful: Riverflow V2 Max Preview",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "sourceful/riverflow-v2-pro",
		Name:     "Sourceful: Riverflow V2 Pro",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "sourceful/riverflow-v2-standard-preview",
		Name:     "Sourceful: Riverflow V2 Standard Preview",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
	{
		Provider: "openrouter",
		ID:       "x-ai/grok-imagine-image-quality",
		Name:     "xAI: Grok Imagine Image Quality",
		API:      "openrouter-images",
		BaseURL:  "https://openrouter.ai/api/v1",
		EnvKey:   "OPENROUTER_API_KEY",
		Input:    []string{"text", "image"},
		Output:   []string{"image"},
		Cost:     Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	},
}
